version: '3.8'

services:
  web:
    image: lasso:v1.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${LOCAL_SERVER_PORT}:${CONTAINER_SERVER_PORT}"
    environment:
      - PORT=${CONTAINER_SERVER_PORT}
    volumes:
      - .:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
